name: Continuous Deployment (CD)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Compose
        run: |
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
          mkdir -p $DOCKER_CONFIG/cli-plugins
          curl -SL https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-linux-x86_64  -o $DOCKER_CONFIG/cli-plugins/docker-compose
          chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
          # Add to PATH
          export PATH="$DOCKER_CONFIG/cli-plugins:$PATH"
          # Test it works
          docker compose version

      - name: Deploy services with Docker Compose
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/quizzapp
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
          SPRING_JPA_HIBERNATE_DDL_AUTO: update
        run: |
          # Make sure PATH is still set
          export PATH="$HOME/.docker/cli-plugins:$PATH"
          docker-compose -f docker-compose.yml pull || echo "No images to pull"
          docker-compose -f docker-compose.yml up -d --build
